### ISSUE TITLE
Trajectory followed by the arm

### ISSUE THREAD

**Issue by marleyshan21** [allenai/manipulathor#9]
Hi, 

We are working on rearranging objects on a table. How do we get information about the trajectory being followed between a pickup and a release of an object in manipulathor? 
1. We would like to get a list of points that belong to the trajectory that the arm follows
2. Is it possible to integrate other trajectory planers with manipulathor?

The ai2thor version I'm using is 3.3.4.

**Comment by ehsanik** [comment]
Hi,

I recommend looking at the implementation of how we record the sequence of actions that are taken by the agent before reading the following response ([implemented here](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_viz.py#L97) and [here](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_tasks.py#L282)). It'll help a lot to understand how to record a trajectory or the sequence of actions that the agent has taken. 

1. You can get the current location of the arm in the agent's coordinate or world coordinate from [this](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_environment.py#L250) and [this](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_environment.py#L267) function.  Then using the same method for recording the sequence of actions taken by the agent [here](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_tasks.py#L282), you can save the trajectory. 
2. Yes it is, you'd need to use the action ```MoveArm``` and depending on your planner choose the appropriate coordinate space from [here](https://ai2thor.allenai.org/manipulathor/documentation/#MoveArm-coordinatespace).

I'm closing the issue for now but let us know if you have any other questions.

**Comment by marleyshan21** [comment]
@ehsanik 
Thanks for your response. I am able to understand getting the current location of the arm. As a beginner,  I am struggling to understand the second part of 1 - the recording part of the sequence of actions and inferring the trajectory from it. We have two actions pickup and release. 
1. Could you give a tiny explanation on the part where we are actually finding the points in the world space that are a part of the trajectory between pickup and release?
2. In  ai2thor.util.metrics I observed a function, get_shortest_path_to_point. But this is for the robot's movement in RoboThor. Do we have a similar function in manipulathor that gives us a dict of the points the arm passes through while going to the target location?

**Comment by ehsanik** [comment]
@marleyshan21 Sure here are some more details. Let me know if you need more clarification, 

1. Basically after taking each action, you can get the current location of the arm from the environment. you need to record that somehow in the environment. My suggestion for you is to do the same approach we took to record the actions that are taken, however, you can choose to use any other recording method that you'd like. So for your use case, you only need to record the arm location (which can be obtained from the environment as described above) for the steps you take between picking up the object and dropping it off.
2. Unfortunately, calculating the shortest path for agent movements in a grid world is much easier than calculating the shortest path in a continuous 3d environment (because of the arm continuous movements in  3D space). Therefore, we do not provide the function you mentioned for arm movements.

**Comment by marleyshan21** [comment]
Oh Okay. It's clearer now. Thanks.

**Comment by marleyshan21** [comment]
@ehsanik 
What trajectory planner is the manipulathor arm using?

**Comment by ehsanik** [comment]
We use PPO to learn a policy that chooses an action based on the current and previous observations.

**Comment by marleyshan21** [comment]
Hi @ehsanik, thats not what i had meant. 
Which planner is being used to move the arm from one point to another ? Is it like RRT etc or a classical IK solver?

**Comment by ehsanik** [comment]
Oh I see. It's a classical IK Solver.

**Comment by marleyshan21** [comment]
Thanks!
